### ISSUE TITLE
Trivial: Disappear Setting

### ISSUE THREAD

**Issue by jwfunk** [sampocs/CS506_Momentum#24]
After setting the habit to disappear and saving it in the settings tab, the habit does not disappear when it's completed. Additionally, when returning to the settings tab after it is saved, canceling the edit and reopening the habit edit screen the setting reverts back to change color.

**Comment by sampocs** [comment]
@jwfunk Can you confirm that the option to choose whether to change color or disappear only appeared when editing a habit and NOT when adding a habit for the first time?

We disappearing action was not finished at the end of the iteration so we decided to take out the toggle in the Add a Habit screen but must have forgotten to take it out of the Edit Habit screen.

**Comment by jwfunk** [comment]
It not there when initially creating a habit

**Comment by sampocs** [comment]
Issue is solved in most recent master branch.
