### ISSUE TITLE
Trivial: Subtask Naming

### ISSUE THREAD

**Issue by jwfunk** [sampocs/CS506_Momentum#26]
Subtasks can have the same name as the habits which could potentially confuse the user when that subtask is displayed at the same time as the habit.

**Comment by sampocs** [comment]
We've decided it does not makes sense to prevent this functionality for the user. For instance, if they want to repeat a task multiple times, they may want to make multiple subtasks with the same name for each repetition. If the user finds it would be confusing to have the same subtask name as a habit name, then they can simply not create a subtask with that name.
