### ISSUE TITLE
Blocker: Putting a decimal place in the Measurements field will produce an error

### ISSUE THREAD

**Issue by jwfunk** [sampocs/CS506_Momentum#28]
Putting a decimal place in the Measurements field will produce an error

**Comment by sampocs** [comment]
I've tried this and it did not result in an error. Can you describe the steps you took / when the error occurred?

**Comment by jwfunk** [comment]
Edit an existing task to have a measurement. Put .2 in for the number and any label. Click save and an error appears

**Comment by sampocs** [comment]
resolved
