### ISSUE TITLE
Blocker : New Screen/Clicking Errors

### ISSUE THREAD

**Issue by nisler** [sampocs/CS506_Momentum#37]
Each time I click on something, an error is displayed covering the entire app screen.

After Clicking Login:
![after clicking login](https://user-images.githubusercontent.com/43834186/56776638-24659000-6793-11e9-8b92-44188664a1e5.jpg)

After Clicking A Habit:
![after_clicking_a_habit](https://user-images.githubusercontent.com/43834186/56776640-292a4400-6793-11e9-9783-e54d11b9b077.jpg)

After Moving a Habit in Settings:
![after_moving_task_item](https://user-images.githubusercontent.com/43834186/56776646-321b1580-6793-11e9-8853-4ca4f1357b07.jpg)

Clicking on a Date:
![clicked_on_date](https://user-images.githubusercontent.com/43834186/56776652-37786000-6793-11e9-8063-958b61a4fc84.jpg)

Startup:
![startup](https://user-images.githubusercontent.com/43834186/56776668-43642200-6793-11e9-9ddd-abd2a0cb912b.jpg)

**Comment by sampocs** [comment]
This app is intended for iOS only. I believe your issues are related to Android.
