### ISSUE TITLE
Critical : App Idling/Running Warnings

### ISSUE THREAD

**Issue by nisler** [sampocs/CS506_Momentum#39]
Just leaving my phone (running Android OS) sit/idle caused warnings to accumulate:
![idle multi](https://user-images.githubusercontent.com/43834186/56776844-064c5f80-6794-11e9-8e9a-23ea51ab385e.jpg)

![idle 1](https://user-images.githubusercontent.com/43834186/56776848-09475000-6794-11e9-9c6c-2a8a2a7f0192.jpg)

![idle 2](https://user-images.githubusercontent.com/43834186/56776852-0c424080-6794-11e9-9c20-4c79b67dddb8.jpg)

**Comment by sampocs** [comment]
This app was built for iOS only. I believe your issue may be Android related.
